### ISSUE TITLE
postgresql  numeric 无法正确对应javaBean 类型

### ISSUE THREAD

**Issue by ESHidden** [baomidou/mybatisplus-boot-starter#5]
postgresql 数据库numeric 类型字段 用AutoGenerator 生成的实体类里都是String类型

**Comment by qmdx** [comment]
请注入相关 db 对应的 ITypeConvert 修改类型字段

**Comment by ESHidden** [comment]
请问大神如何设置？
我这样设置都变成string了，怎么单独修改一种类型
@Component
public class TypeConvert implements ITypeConvert {
    @Override
    public DbColumnType processTypeConvert(String fieldType) {
        String t = fieldType.toLowerCase();
        if ("numeric".equals(t)) {
            return DbColumnType.DOUBLE;
        }
        return DbColumnType.STRING;
    }
}


 config.setTypeConvert(new TypeConvert() {
                        @Override
                        public DbColumnType processTypeConvert(String fieldType) {
                            String t = fieldType.toLowerCase();
                            if ("numeric".equals(t)) {
                                return DbColumnType.DOUBLE;
                            }
                            return super.processTypeConvert(fieldType);
                    }
                })

**Comment by ESHidden** [comment]
if (t.contains("numeric")) {
                                System.out.println("转换类型：" + t+"==>"+DbColumnType.DOUBLE.getType());
                                return DbColumnType.DOUBLE;
                            }
已解决 谢谢！
